services:
  mysql:
    image: mysql:9.4
    container_name: multilab-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: multilab
      MYSQL_ROOT_PASSWORD: root
    volumes:
      -   mysql_data:/var/lib/mysql
    networks:
      -   app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: multilab-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      -   mysql
    networks:
      -   app-network

  app:
    build: .
    container_name: multilab-laravel
    working_dir: /var/www
    volumes:
      -   .:/var/www
      -   vendor:/var/www/vendor
      -   node_modules:/var/www/node_modules
    ports:
      -   "8000:8000"
    depends_on:
      -   mysql
    command: php artisan serve --host=0.0.0.0 --port=8000
    entrypoint: ["sh","/var/www/docker/entrypoint.sh"]
    environment:
      SESSION_DRIVER: file
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
      DB_HOST: mysql
      DB_DATABASE: multilab
      DB_USERNAME: root
      DB_PASSWORD: root
      LOG_CHANNEL: stack
      VIEW_COMPILED_PATH: /tmp/laravel-views
      SESSION_FILES_PATH: /tmp/laravel-sessions
      CACHE_FILE_PATH: /tmp/laravel-cache
    networks:
      -   app-network

  cron:
    build: .
    container_name: multilab-cron
    working_dir: /var/www
    volumes:
      -   .:/var/www
      -   vendor:/var/www/vendor
      -   node_modules:/var/www/node_modules
    depends_on:
      -   mysql
    command: sh -c "while true; do php artisan schedule:run; sleep 60; done"
    entrypoint: ["sh","/var/www/docker/entrypoint.sh"]
    environment:
      SESSION_DRIVER: file
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
      DB_HOST: mysql
      DB_DATABASE: multilab
      DB_USERNAME: root
      DB_PASSWORD: root
      LOG_CHANNEL: stack
      VIEW_COMPILED_PATH: /tmp/laravel-views
      SESSION_FILES_PATH: /tmp/laravel-sessions
      CACHE_FILE_PATH: /tmp/laravel-cache
    networks:
      -   app-network

volumes:
  mysql_data:
  vendor:
  node_modules:

networks:
  app-network:
